{{- if .Values.logger.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hyperflexsizer.fullname" . }}-logger-conf
  labels:
    snappyflow/compname: hxstage
    snappyflow/appname: hxsizer-stage
    app: {{ template "hyperflexsizer.name" . }}
    chart: {{ template "hyperflexsizer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "logger_config/*").AsConfig | indent 2 }}
{{- end }}